# Generated by Django 5.0.1 on 2024-01-26 22:56

import bunkergames.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=bunkergames.models.generate_id, max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(32)])),
                ('started', models.BooleanField(default=False)),
            ],
        ),
    ]
