# Generated by Django 5.0.1 on 2024-01-25 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)])),
                ('started', models.BooleanField(default=True)),
            ],
        ),
    ]
