# Generated by Django 5.0.1 on 2024-01-26 02:00

import bunkergames.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkergames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default=bunkergames.models.generate_id, max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
