# Generated by Django 5.0.1 on 2024-01-26 02:10

import bunkergames.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkergames', '0002_alter_game_id_alter_game_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(default=bunkergames.models.generate_id, max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
