# Generated by Django 5.0.1 on 2024-01-25 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bunkergames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('data', models.JSONField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunkergames.game')),
            ],
            options={
                'unique_together': {('game_id', 'username')},
            },
        ),
    ]
