# Generated by Django 5.0.1 on 2024-01-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bunkergames', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('host', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunkergames.game')),
                ('session_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'unique_together': {('game_id', 'session_key'), ('game_id', 'username')},
            },
        ),
    ]
