# Generated by Django 4.2.7 on 2024-01-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunkergames', '0001_initial'),
        ('sessions', '0001_initial'),
        ('bunkerusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='session_key',
            new_name='session',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('game', 'session'), ('game', 'username')},
        ),
    ]
