# Generated by Django 5.0.1 on 2024-01-26 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkergames', '0002_alter_game_id_alter_game_started'),
        ('bunkerusers', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('game_id', 'username')},
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.ForeignKey(default='jbsdj', on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('game_id', 'session_key'), ('game_id', 'username')},
        ),
    ]
