# Generated by Django 4.2.7 on 2024-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkerusers', '0002_rename_game_id_user_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='showman',
            field=models.BooleanField(default=False),
        ),
    ]
